# Generated by Django 4.1.7 on 2023-02-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraEars',
        ),
    ]
