# Generated by Django 4.1.7 on 2023-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('title', '0002_delete_extraears'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target1900',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
    ]
